name: CI
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx release-it --no-git.requireCleanWorkingDir --ci



# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Setup Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '20'

#     - name: Install dependencies
#       run: npm install

#     - name: Build
#       run: npm run build

#     - name: Publish to npm
#       run: npm publish

#     - name: Bump version and push tag
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
#       env:
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#       run: |
#         npm version patch -m "Bump version to %s"
#         git push --follow-tags
